server:
  dataStorage:
    enabled: true
    storageClass: gp2   # Use the gp2 storage class
    size: 10Gi
    accessMode: ReadWriteOnce
  service:
    type: LoadBalancer
    ports:
      - port: 8200
        targetPort: 8200
        protocol: TCP
  affinity: ""
  ha:
    enabled: true
    raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          cluster_name = "vault-integrated-storage"
          storage "raft" {
              path    = "/vault/data/"
          }

          listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = "true"
          }
          service_registration "kubernetes" {}
